### ISSUE TITLE
A question about coco dataset

### ISSUE THREAD

**Issue by GT9505** [tshizys/CoupleNet#2]
Did you use the context prior to the global branch when you get 33.1 mAP result on coco dataset without multi-scale training

**Comment by yousongzhu** [comment]
yes, i added the context prior with the 33.1 mAP.


-----原始邮件-----
发件人:GT9505 <notifications@github.com>
发送时间:2017-10-18 18:42:05 (星期三)
收件人: tshizys/CoupleNet <CoupleNet@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [tshizys/CoupleNet] A question about coco dataset (#2)



Did you use the context prior to the global branch when you get 33.1 mAP result on coco dataset without multi-scale training

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


--

yousong zhu,  postgraduate
National Laboratory of Pattern Recognition(NLPR)
Institute of Automation, Chinese Academy of Sciences(CASIA)
Beijing, P.R.China, 100190
Email: yousong.zhu@nlpr.ia.ac.cn

**Comment by foralliance** [comment]
@tshizys 
about **context prior**, in the code(prototxt) you provide, it doesn't seem to show this part

**Comment by smhyzys** [comment]
@foralliance , the original version of context was implemented by the python code(not elegan), so i did not release the corresponding models and the codes. Recommending to use the context RoIPooling layer (https://github.com/zhaoweicai/mscnn), it is easy to implement the context branches by using the RoIPooling layer.

**Comment by foralliance** [comment]
@smhyzys 
thanks your reply, i will try it

**Comment by foralliance** [comment]
@smhyzys 
with the help of the **roi_pooling layer** in **ms-cnn**, the **context prior** of  **couplenet** can indeed be implemented.

I have another two questions
1. Before these two features are fuse(`concat`), does it need to do some operations (such as **normalization**, which is not done in **ms-cnn**)?
2. In ms-cnn, after features fusion, a `3*3 convolution layer` is added. In couplenet, does it also require additional layer processing? what's the specific form? for example, the convolution kernel size, the output dimension
